version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt  # Hoặc bạn có thể chỉ định 'setup.py'

sphinx:
  configuration: ./source/conf.py  # Đường dẫn tới tệp conf.py của bạn
