version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt  # Hoặc bạn có thể chỉ định 'setup.py'
commands:
  # Cài đặt gói stockvip với python 3.11 theo cách tùy chỉnh
  - python3.10 -m pip install --upgrade --no-cache-dir --use-deprecated=legacy-resolver stockvip
sphinx:
  configuration: ./source/conf.py  # Đường dẫn tới tệp conf.py của bạn
