version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  commands:
    - python3.10 -m pip install -r requirements.txt  # Cài đặt từ requirements.txt
    - python3.10 -m pip install --upgrade --no-cache-dir --use-deprecated=legacy-resolver stockvip  # Cài đặt thêm gói stockvip


sphinx:
  configuration: ./source/conf.py  # Đường dẫn tới tệp conf.py của bạn
